/* 
**  mod_wai.c -- Apache sample wai module
**  [Autogenerated via ``apxs -n wai -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_wai.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /wai in as follows:
**
**    #   apache2.conf
**    LoadModule wai_module modules/mod_wai.so
**    <Location /wai>
**    SetHandler wai
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /wai and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/wai 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_wai.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
static int wai_handler(request_rec *r)
{
    if (strcmp(r->handler, "wai")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_wai.c\n", r);
    return OK;
}

static void wai_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(wai_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA wai_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    wai_register_hooks  /* register hooks                      */
};

